CREATE TABLE IF NOT EXISTS `BRAND`
(
  `BRAND_ID`  BIGINT(20) NOT NULL PRIMARY KEY,
  `BRAND_NAME` VARCHAR(150) NOT NULL
);

CREATE TABLE IF NOT EXISTS `PRICES`
(
  `ID`                BIGINT(20) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `BRAND_ID`          BIGINT(20) NOT NULL,
  `START_DATE` 		    DATETIME NOT NULL,
  `END_DATE` 		      DATETIME NOT NULL,
  `PRICE_LIST` 		    TINYINT NOT NULL,
  `PRODUCT_ID`        BIGINT(20)  NOT NULL,
  `PRIORITY`  TINYINT   NOT NULL,
  `PRICE`  FLOAT   NOT NULL,
  `CURR`  VARCHAR(20)   NOT NULL,
  CONSTRAINT `FK_BRAND_ID_BRAND`
    FOREIGN KEY (BRAND_ID) REFERENCES `BRAND` (BRAND_ID)
);